import * as THREE from 'three';
import {track,LENGTH,LAPS,createRace,updateRace,standings} from './race.js';
import './style.css';
document.querySelector('#app').innerHTML=`<canvas id="view" aria-label="3D racing scene"></canvas><header><span class="brand">COASTLINE <b>RUSH</b></span><button id="pause">Pause</button><button id="restart">Restart</button></header><section class="position"><small>POSITION</small><strong id="position">8 / 8</strong><ol id="leaders"></ol></section><section class="timing"><small>LAP <b id="lap">1 / 3</b></small><p>TIME <span id="time">0:00.00</span></p><p>BEST <span id="best">-</span></p></section><canvas id="map" width="180" height="180" aria-label="Race minimap"></canvas><section class="speed"><strong id="speed">0</strong><small>KM/H</small><label>NITRO <progress id="nitro" max="100" value="100"></progress></label></section><div id="overlay"><div class="card"><small>THREE.JS ARCADE RACING</small><h1>Coastline Rush</h1><p>Three laps. Seven rivals. One coastal circuit.</p><p>W / ↑ accelerate · S / ↓ brake<br>A D / ← → steer · Shift nitro · C camera · Esc pause</p><button id="start">Start race</button><p class="hint">Original procedural art. Arcade physics.</p></div></div><div class="touch"><button data-key="ArrowLeft">◀</button><button data-key="ArrowRight">▶</button><button data-key="Shift">NITRO</button><button data-key="ArrowDown">BRAKE</button><button data-key="ArrowUp">GO</button></div><div id="error" role="alert"></div>`;
const $=id=>document.getElementById(id),scene=new THREE.Scene();scene.background=new THREE.Color('#93cbe1');scene.fog=new THREE.Fog('#93cbe1',180,700);
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('view'),antialias:true});}catch(e){$('error').textContent='WebGL is unavailable. Enable hardware acceleration and reload.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const camera=new THREE.PerspectiveCamera(65,1,.1,1500);scene.add(new THREE.HemisphereLight(0xd9f2ff,0x565b40,2));const sun=new THREE.DirectionalLight(0xffe9c9,3);sun.position.set(100,180,80);scene.add(sun);
const mats={road:new THREE.MeshStandardMaterial({color:0x353e45,roughness:.95}),land:new THREE.MeshStandardMaterial({color:0x728756}),rock:new THREE.MeshStandardMaterial({color:0x939280}),rail:new THREE.MeshStandardMaterial({color:0xd3dbd9,metalness:.7,roughness:.4}),white:new THREE.MeshStandardMaterial({color:0xf4e8ba}),water:new THREE.MeshStandardMaterial({color:0x1685a1,metalness:.35,roughness:.3}),dark:new THREE.MeshStandardMaterial({color:0x101a26,roughness:.4}),red:new THREE.MeshBasicMaterial({color:0xff304f})};
function box(w,h,d,mat,x,y,z,parent=scene){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
box(1300,2,1300,mats.water,0,-7,0);box(250,12,370,mats.land,0,-7,0);
function ribbon(offset,width,mat){const positions=[],indices=[];for(let i=0;i<=400;i++){const p=track(i/400*LENGTH),nx=Math.cos(p.heading),nz=-Math.sin(p.heading);for(const lane of [offset-width/2,offset+width/2])positions.push(p.x+nx*lane,p.y,p.z+nz*lane);if(i<400){const a=i*2;indices.push(a,a+2,a+1,a+1,a+2,a+3);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setIndex(indices);g.computeVertexNormals();const m=new THREE.Mesh(g,mat);m.receiveShadow=true;scene.add(m);}
ribbon(0,15,mats.road);ribbon(-7.1,.2,mats.white);ribbon(7.1,.2,mats.white);
for(let i=0;i<150;i++){const s=i/150*LENGTH,p=track(s);for(const side of [-1,1]){const lane=side*8.1,nx=Math.cos(p.heading),nz=-Math.sin(p.heading);const rail=box(.2,.7,8,mats.rail,p.x+nx*lane,p.y+1,p.z+nz*lane);rail.rotation.y=p.heading;}
 if(i%2===0){const stripe=box(.18,.02,3,mats.white,p.x,p.y+.03,p.z);stripe.rotation.y=p.heading;}
 if(i%3===0){const lane=-17-i%5,p1={x:p.x+Math.cos(p.heading)*lane,z:p.z-Math.sin(p.heading)*lane};const trunk=box(.6,4,.6,mats.rock,p1.x,p.y+2,p1.z);const tree=new THREE.Mesh(new THREE.ConeGeometry(2.5,8,7),mats.land);tree.position.set(p1.x,p.y+7,p1.z);scene.add(tree);}}
for(let i=0;i<22;i++){const a=i*2.399,r=75+(i%4)*18;const mountain=new THREE.Mesh(new THREE.ConeGeometry(25+i%4*8,60+i%5*13,6),mats.rock);mountain.position.set(Math.sin(a)*r,12,Math.cos(a)*r);scene.add(mountain);}
for(let i=0;i<15;i++){const p=track(210+i*15),lane=-26-i%3*8,x=p.x+Math.cos(p.heading)*lane,z=p.z-Math.sin(p.heading)*lane;const wall=new THREE.MeshStandardMaterial({color:[0xe8ca91,0xd7a484,0xf3dab7][i%3]});box(7,9+i%3*3,7,wall,x,p.y+4,z);const roof=new THREE.Mesh(new THREE.ConeGeometry(6,3,4),new THREE.MeshStandardMaterial({color:0x985a40}));roof.position.set(x,p.y+10+i%3*3,z);roof.rotation.y=Math.PI/4;scene.add(roof);}
const colors=[0x19a0ff,0xffa230,0xf6f6ee,0xe83543,0xa48af5,0x42d7bd,0xf0d652,0x517ab7];
function car(color){const g=new THREE.Group(),paint=new THREE.MeshStandardMaterial({color,metalness:.5,roughness:.28});box(1.9,.55,3.8,paint,0,.55,0,g);box(1.55,.6,1.6,mats.dark,0,1.05,-.2,g);box(2,.12,.5,mats.dark,0,1.15,-1.7,g);box(.12,.6,.12,mats.dark,-.7,.85,-1.7,g);box(.12,.6,.12,mats.dark,.7,.85,-1.7,g);box(1.55,.12,.06,mats.red,0,.62,-1.93,g);for(const x of [-1,1])for(const z of [-1.2,1.2]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.4,.4,.25,12),mats.dark);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.4,z);g.add(wheel);}scene.add(g);return g;}
const cars=colors.map(car);const keys=new Set();let race=createRace(),cameraMode=0,last=performance.now();
function clearKeys(){keys.clear();}addEventListener('blur',()=>{clearKeys();if(race.phase==='racing')pause();});
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.repeat)return;if(e.key==='Escape')pause();if(e.key.toLowerCase()==='c')cameraMode=(cameraMode+1)%2;});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key.toLowerCase());});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key.toLowerCase()));}
function start(){race.phase='racing';$('overlay').hidden=true;clearKeys();}
function pause(){if(!['racing','paused'].includes(race.phase))return;race.phase=race.phase==='racing'?'paused':'racing';$('overlay').hidden=race.phase==='racing';if(race.phase==='paused')show('Race paused','Your race is waiting.','Resume',start);clearKeys();}
function show(title,text,label,action){$('overlay').hidden=false;$('overlay').querySelector('.card').innerHTML=`<h1>${title}</h1><p>${text}</p><button id="start">${label}</button>`;$('start').onclick=action;}
function restart(){race=createRace();show('Ready to race?','Three laps around the coastline.','Start race',start);clearKeys();}
$('start').onclick=start;$('pause').onclick=pause;$('restart').onclick=restart;
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
function format(t){return `${Math.floor(t/60)}:${(t%60).toFixed(2).padStart(5,'0')}`;}
const map=$('map').getContext('2d');function drawMap(){map.clearRect(0,0,180,180);map.strokeStyle='#92b5c5';map.lineWidth=6;map.beginPath();for(let i=0;i<=100;i++){const p=track(i/100*LENGTH),x=90+p.x*.3,y=90+p.z*.3;i?map.lineTo(x,y):map.moveTo(x,y);}map.stroke();[race.player,...race.bots].forEach((a,i)=>{const p=track(a.s);map.fillStyle=i===0?'#30dbff':'#ff965c';map.beginPath();map.arc(90+p.x*.3,90+p.z*.3,i===0?5:3,0,Math.PI*2);map.fill();});}
function frame(now){const dt=Math.max(0,(now-last)/1000);last=now;const old=race.phase;updateRace(race,{throttle:keys.has('w')||keys.has('arrowup'),brake:keys.has('s')||keys.has('arrowdown'),steer:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),nitro:keys.has('shift')},dt);
 [race.player,...race.bots].forEach((a,i)=>{const p=track(a.s);cars[i].position.set(p.x+Math.cos(p.heading)*a.lane,p.y+.08,p.z-Math.sin(p.heading)*a.lane);cars[i].rotation.y=p.heading;});
 const player=cars[0],forward=new THREE.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y)),desired=player.position.clone().addScaledVector(forward,cameraMode===0?-9:-.5).add(new THREE.Vector3(0,cameraMode===0?4:1.8,0));camera.position.lerp(desired,Math.min(1,dt*7));camera.lookAt(player.position.clone().addScaledVector(forward,18).add(new THREE.Vector3(0,1.5,0)));
 const order=standings(race);$('position').textContent=`${order.indexOf(race.player)+1} / 8`;$('leaders').innerHTML=order.map(a=>`<li class="${a===race.player?'you':''}">${a.name}</li>`).join('');$('lap').textContent=`${race.lap} / ${LAPS}`;$('time').textContent=format(race.time);$('best').textContent=race.best===null?'-':format(race.best);$('speed').textContent=Math.round(race.player.speed*3.6);$('nitro').value=race.nitro;$('view').classList.toggle('contact',race.contact>0);drawMap();
 if(old==='racing'&&race.phase==='finished'){show('Race complete',`Position ${order.indexOf(race.player)+1} / 8 · ${format(race.time)}`,'Race again',restart);try{const best=Number(localStorage.getItem('coastline-best')||Infinity);localStorage.setItem('coastline-best',String(Math.min(best,race.time)));}catch{}}
 renderer.render(scene,camera);requestAnimationFrame(frame);}
requestAnimationFrame(frame);
// Read-only diagnostics for browser validation; no gameplay shortcuts.
window.racingDiagnostics=()=>({phase:race.phase,time:race.time,speed:race.player.speed,distance:race.player.s,nitro:race.nitro,lap:race.lap,webgl:!!renderer.getContext()});
